# ================================================
# SECRETS SCANNING JOBS
# ================================================
# Detecta secretos, credenciales y tokens hardcodeados
# usando detect-secrets
# ================================================

secrets-scan:api:
  extends:                                # Hereda configuración de templates
    - .scan_template                      # Template base para scans (Python, runner sin Docker)
    - .rules_api                          # Reglas: solo si cambia api/
  stage: secrets-scan                     # Etapa secrets-scan (1ra etapa)
  script:                                 # Comandos a ejecutar
    - echo "Escaneando secretos en API..."  # Mensaje
    - pip install detect-secrets          # Instala detect-secrets (herramienta de Yelp)
    - detect-secrets scan api/ > secrets-api-report.json || echo '{}' > secrets-api-report.json  # Escanea carpeta api/, genera JSON (|| echo crea JSON vacío si falla)
    - echo "✓ Escaneo de secretos completado para API"  # Mensaje de éxito
  artifacts:                              # Artifacts (archivos guardados)
    paths:                                # Rutas a guardar
      - secrets-api-report.json           # Reporte JSON de detect-secrets
    expire_in: 1 week                     # Expira en 1 semana
    when: always                          # Guardar siempre (incluso si falla)

secrets-scan:web:
  extends:                                # Hereda configuración
    - .scan_template                      # Template base para scans
    - .rules_web                          # Reglas: solo si cambia web/
  stage: secrets-scan                     # Etapa secrets-scan
  script:                                 # Comandos
    - echo "Escaneando secretos en Web..."  # Mensaje
    - pip install detect-secrets          # Instala detect-secrets
    - detect-secrets scan web/ > secrets-web-report.json || echo '{}' > secrets-web-report.json  # Escanea web/, genera JSON
    - echo "✓ Escaneo de secretos completado para Web"  # Éxito
  artifacts:                              # Artifacts
    paths:                                # Archivos a guardar
      - secrets-web-report.json           # Reporte JSON
    expire_in: 1 week                     # 1 semana
    when: always                          # Siempre guardar

secrets-scan:notifications:
  extends:                                # Hereda configuración
    - .scan_template                      # Template base
    - .rules_notifications                # Reglas: solo si cambia notifications/
  stage: secrets-scan                     # Etapa secrets-scan
  script:                                 # Comandos
    - echo "Escaneando secretos en Notifications..."  # Mensaje
    - pip install detect-secrets          # Instala detect-secrets
    - detect-secrets scan notifications/ > secrets-notifications-report.json || echo '{}' > secrets-notifications-report.json  # Escanea notifications/
    - echo "✓ Escaneo de secretos completado para Notifications"  # Éxito
  artifacts:                              # Artifacts
    paths:                                # Archivos
      - secrets-notifications-report.json  # Reporte JSON
    expire_in: 1 week                     # 1 semana
    when: always                          # Siempre

secrets-scan:nginx:
  extends:                                # Hereda configuración
    - .scan_template                      # Template base
    - .rules_nginx                        # Reglas: solo si cambia nginx/
  stage: secrets-scan                     # Etapa secrets-scan
  script:                                 # Comandos
    - echo "Escaneando secretos en Nginx..."  # Mensaje
    - pip install detect-secrets          # Instala detect-secrets
    - detect-secrets scan nginx/ > secrets-nginx-report.json || echo '{}' > secrets-nginx-report.json  # Escanea nginx/
    - echo "✓ Escaneo de secretos completado para Nginx"  # Éxito
  artifacts:                              # Artifacts
    paths:                                # Archivos
      - secrets-nginx-report.json         # Reporte JSON
    expire_in: 1 week                     # 1 semana
    when: always                          # Siempre
